# Generated by Django 3.1 on 2020-09-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaskCCTV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('set_mask', models.BooleanField()),
            ],
        ),
    ]
