# Generated by Django 3.1 on 2020-09-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaskCCTV', '0004_auto_20200903_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskinfo',
            name='adress',
            field=models.CharField(choices=[('남춘천역', '강원도 춘천시 효자동 남춘천역'), ('강남역', '서울시 강남구 강남역'), ('사릉역', '경기도 남양주시 사릉역')], default='남춘천역', help_text='CCTV 주소', max_length=20),
        ),
    ]
